//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AEPM_GetMaster.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServices")]
    public interface IServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/GetMaster", ReplyAction="http://tempuri.org/IServices/GetMasterResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CrossPart))]
        AEPM_GetMaster.ServiceReference1.GetMasterResult GetMaster(string PartNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/AddMaster", ReplyAction="http://tempuri.org/IServices/AddMasterResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CrossPart))]
        AEPM_GetMaster.ServiceReference1.AddMasterResult AddMaster(string UserID, AEPM_GetMaster.ServiceReference1.CrossPart[] CrossPartList, bool Branded, string Commodity_Code, short Level, string Status, bool Returnable, string Tariff_Code, string AMSC, int Technical_Qty, int Service_Life, string Package_Code, string Information);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://tempuri.org/encoded")]
    public partial class GetMasterResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool brandedField;
        
        private string commodity_CodeField;
        
        private short levelField;
        
        private string statusField;
        
        private bool returnableField;
        
        private string tariff_CodeField;
        
        private string aMSCField;
        
        private int technical_QtyField;
        
        private int service_LifeField;
        
        private string package_CodeField;
        
        private string informationField;
        
        private string userIDField;
        
        private System.DateTime dateCreatedField;
        
        private CrossPart[] crossPartListField;
        
        private bool successField;
        
        private string errorField;
        
        /// <remarks/>
        public bool Branded {
            get {
                return this.brandedField;
            }
            set {
                this.brandedField = value;
                this.RaisePropertyChanged("Branded");
            }
        }
        
        /// <remarks/>
        public string Commodity_Code {
            get {
                return this.commodity_CodeField;
            }
            set {
                this.commodity_CodeField = value;
                this.RaisePropertyChanged("Commodity_Code");
            }
        }
        
        /// <remarks/>
        public short Level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
                this.RaisePropertyChanged("Level");
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        public bool Returnable {
            get {
                return this.returnableField;
            }
            set {
                this.returnableField = value;
                this.RaisePropertyChanged("Returnable");
            }
        }
        
        /// <remarks/>
        public string Tariff_Code {
            get {
                return this.tariff_CodeField;
            }
            set {
                this.tariff_CodeField = value;
                this.RaisePropertyChanged("Tariff_Code");
            }
        }
        
        /// <remarks/>
        public string AMSC {
            get {
                return this.aMSCField;
            }
            set {
                this.aMSCField = value;
                this.RaisePropertyChanged("AMSC");
            }
        }
        
        /// <remarks/>
        public int Technical_Qty {
            get {
                return this.technical_QtyField;
            }
            set {
                this.technical_QtyField = value;
                this.RaisePropertyChanged("Technical_Qty");
            }
        }
        
        /// <remarks/>
        public int Service_Life {
            get {
                return this.service_LifeField;
            }
            set {
                this.service_LifeField = value;
                this.RaisePropertyChanged("Service_Life");
            }
        }
        
        /// <remarks/>
        public string Package_Code {
            get {
                return this.package_CodeField;
            }
            set {
                this.package_CodeField = value;
                this.RaisePropertyChanged("Package_Code");
            }
        }
        
        /// <remarks/>
        public string Information {
            get {
                return this.informationField;
            }
            set {
                this.informationField = value;
                this.RaisePropertyChanged("Information");
            }
        }
        
        /// <remarks/>
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
                this.RaisePropertyChanged("UserID");
            }
        }
        
        /// <remarks/>
        public System.DateTime DateCreated {
            get {
                return this.dateCreatedField;
            }
            set {
                this.dateCreatedField = value;
                this.RaisePropertyChanged("DateCreated");
            }
        }
        
        /// <remarks/>
        public CrossPart[] CrossPartList {
            get {
                return this.crossPartListField;
            }
            set {
                this.crossPartListField = value;
                this.RaisePropertyChanged("CrossPartList");
            }
        }
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("Success");
            }
        }
        
        /// <remarks/>
        public string Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("Error");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://tempuri.org/encoded")]
    public partial class CrossPart : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string brandField;
        
        private string partNumberField;
        
        /// <remarks/>
        public string Brand {
            get {
                return this.brandField;
            }
            set {
                this.brandField = value;
                this.RaisePropertyChanged("Brand");
            }
        }
        
        /// <remarks/>
        public string PartNumber {
            get {
                return this.partNumberField;
            }
            set {
                this.partNumberField = value;
                this.RaisePropertyChanged("PartNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://tempuri.org/encoded")]
    public partial class AddMasterResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        private string errorField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("Success");
            }
        }
        
        /// <remarks/>
        public string Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("Error");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicesChannel : AEPM_GetMaster.ServiceReference1.IServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicesClient : System.ServiceModel.ClientBase<AEPM_GetMaster.ServiceReference1.IServices>, AEPM_GetMaster.ServiceReference1.IServices {
        
        public ServicesClient() {
        }
        
        public ServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AEPM_GetMaster.ServiceReference1.GetMasterResult GetMaster(string PartNumber) {
            return base.Channel.GetMaster(PartNumber);
        }
        
        public AEPM_GetMaster.ServiceReference1.AddMasterResult AddMaster(string UserID, AEPM_GetMaster.ServiceReference1.CrossPart[] CrossPartList, bool Branded, string Commodity_Code, short Level, string Status, bool Returnable, string Tariff_Code, string AMSC, int Technical_Qty, int Service_Life, string Package_Code, string Information) {
            return base.Channel.AddMaster(UserID, CrossPartList, Branded, Commodity_Code, Level, Status, Returnable, Tariff_Code, AMSC, Technical_Qty, Service_Life, Package_Code, Information);
        }
    }
}
